# Generated by Django 3.0 on 2020-01-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_tutor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='name',
        ),
    ]
