# Generated by Django 3.0.2 on 2020-04-21 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu', '0004_auto_20200326_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matched_Request',
            new_name='MatchedRequest',
        ),
    ]
