# Generated by Django 3.0.2 on 2020-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_auto_20200421_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='groupMatch',
        ),
        migrations.AddField(
            model_name='tutor',
            name='group_of_student',
            field=models.ManyToManyField(blank=True, related_name='list_of_student', to='edu.Tutor'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='group_of_tutor',
            field=models.ManyToManyField(blank=True, related_name='list_of_tutor', to='edu.Tutor'),
        ),
    ]
