# Generated by Django 3.0.2 on 2020-04-22 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu', '0006_auto_20200421_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('gender', models.TextField(blank=True, default='')),
                ('city', models.TextField(blank=True, default='')),
                ('expert', models.TextField(blank=True, default='')),
                ('students', models.ManyToManyField(blank=True, related_name='list_of_student', to='edu.UserAccount')),
                ('tutors', models.ManyToManyField(blank=True, related_name='list_of_tutor', to='edu.UserAccount')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_tutor', to='edu.UserAccount'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='edu.UserAccount'),
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
